version: '3'

services:
  console-manager:
    image: console-manager
    environment:
    - TZ=Etc/UTC
    - DEBUG=1
    - SSH_PORT=8888
    - FRONTEND_PORT=4000
    - AGENT_PORT=9999
    - WRITE_BUFFER_SIZE=1024
    - READ_BUFFER_SIZE=1024
    - AGENT_TERMINAL_WAIT_TIMEOUT=5
    ports:
    - "8888:8888"
    - "9999:9999"
    - "4000:4000"

  console-agent:
    image: console-agent
    environment:
    - TZ=Etc/UTC
    - SERVER_AGENT=console-manager:9999
    - SERVER_SSH=console-manager:8888
    - SSH_PORT=:22
    - DEBUG=1
    - TOKEN=0000000001
    - SSH_PASSWORD=pass2
    - ENV SSH_USER=root
    links:
    - console-manager
    depends_on:
    - console-manager